#加密参数
jasypt:
  encryptor:
    password: hellojasypt
#tomcat 端口
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  session:
    #session超时时间 秒
    timeout: 1800

#核心Logger（包含嵌入式容器、hibernate、spring）会输出更多内容，
#但是你自己应用的日志并不会输出为DEBUG级别
debug: true

spring:
  #热部署生效
  devtools:
    restart:
      enabled: true
  #时间戳统一转换
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
  data:
    #mongodb数据源配置
    mongodb:
      host: 192.168.88.128
      port: 27017
      database: testDB
      repositories:
        enabled: true
    #solr数据源配置
    solr:
      host: http://192.168.88.128:8983/solr
      repositories:
        enabled: true
  #redis 数据源配置
  redis:
    # Redis服务器地址
    host: 192.168.88.128
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ENC(356IXRJuIUZGToRMUG375+pm5hnmyqM4)
    # 连接超时时间（毫秒）
    timeout: 60000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 1
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 60000
  #数据源配置
  datasource:
    #mysql+druid数据库连接池
    druid:
      #name: 如果存在多数据源，监控的时候区分 如果不设置 默认DataSource-" + System.identityHashCode(this)
      #mysql数据源配置
      url: jdbc:mysql://192.168.88.128:3306/solrdb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
      username: root
      password: ENC(356IXRJuIUZGToRMUG375+pm5hnmyqM4)
      driver-class-name: com.mysql.jdbc.Driver
      db-type: mysql
      #druid连接池配置
      #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 1
      #最小连接池数量
      min-idle: 1
      #最大连接池数量
      max-active: 3
      #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      max-wait: 60000
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 'x'
      filters: stat,wall,slf4j
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
mybatis:
  configuration:
    #记录到日志
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    #控制台输出sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mybatis 别名
  type-aliases-package: com.bonc.entity
  #mapper xml 扫描
  mapper-locations: classpath:com/bonc/mapper/*Mapper.xml
