#加密参数
jasypt:
  encryptor:
    password: hellojasypt
#tomcat 配置
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  session:
    #session超时时间 秒
    timeout: 1800

#核心Logger（包含嵌入式容器、hibernate、spring）会输出更多内容，
#但是你自己应用的日志并不会输出为DEBUG级别
#debug: true

banner:
  charset: UTF-8

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

  #热部署生效
  devtools:
    restart:
      enabled: true
#  时间戳统一转换
#  jackson:
#    date-format: "yyyy-MM-dd HH:mm:ss"
#    time-zone: "GMT+8"
  #redis 数据源配置
  redis:
    # Redis服务器地址
    host: 192.168.88.129
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ENC(356IXRJuIUZGToRMUG375+pm5hnmyqM4)
    # 连接超时时间（毫秒）
    timeout: 60000
    #连接池
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 3
      # 连接池中的最大空闲连接
      max-idle: 1
      # 连接池中的最小空闲连接
      min-idle: 1
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 60000
  data:
    #mongodb数据源配置
    mongodb:
      host: 192.168.88.129
      port: 27017
#      认证数据库
      authentication-database: admin
      username: mace
      password: ENC(356IXRJuIUZGToRMUG375+pm5hnmyqM4)
#      用户使用数据库
      database: testDB
      repositories:
        enabled: true

    #solr数据源配置
    solr:
      host: http://192.168.88.129:8983/solr
      username: mace
      password: ENC(356IXRJuIUZGToRMUG375+pm5hnmyqM4)
#      最大连接数
      maxConnections: 8
#      每个主机最大连接数
      maxConnectionsPerHost: 2
#      遵循重定向
      followRedirects: false
      repositories:
        enabled: true
    #redis数据源配置
    redis:
      repositories:
        enabled: true
  #数据源配置
  datasource:
#    数据库连接池 druid
    type: com.alibaba.druid.pool.DruidDataSource
    #master-mysql数据源配置
    master:
      url: jdbc:mysql://192.168.88.129:3306/mmall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
      username: root
      password: ENC(356IXRJuIUZGToRMUG375+pm5hnmyqM4)
      driver-class-name: com.mysql.jdbc.Driver
      masterMapperLocations: classpath:mapper/*Mapper.xml
    #cluster-mysql数据源配置
    cluster:
      url: jdbc:mysql://192.168.88.129:3306/solrdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
      username: root
      password: ENC(356IXRJuIUZGToRMUG375+pm5hnmyqM4)
      driver-class-name: com.mysql.jdbc.Driver
      clusterMapperLocations: classpath:mapper_solr/*Mapper.xml
    #mysql+druid数据库连接池
    druid:
      #name: 如果存在多数据源，监控的时候区分 如果不设置 默认DataSource-" + System.identityHashCode(this)
#      name: DataSource-SpringBootDemo
#      url: jdbc:mysql://192.168.88.129:3306/*?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
#      username: root
#      password: ENC(356IXRJuIUZGToRMUG375+pm5hnmyqM4)
#      driver-class-name: com.mysql.jdbc.Driver
      db-type: mysql
      #druid连接池配置
      async-init: true
      async-close-connection-enable: true
      #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 1
      #最小连接池数量
      min-idle: 1
      #最大连接池数量
      max-active: 3
      #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      max-wait: 60000
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      #pool-prepared-statements: true
      #max-pool-prepared-statement-per-connection-size: 20
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #mysql检查数据库连接 oracle select 1 from dual
      validation-query: select 1
      #stat 监控 wall sql注入
      filters: stat,wall
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000

  #thymeleaf模板
  thymeleaf:
#    启用模板缓存
    cache: false


#mybatis配置
mybatis:
  configuration:
    #记录到日志
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    #开启驼峰转换
    map-underscore-to-camel-case: true
    #使全局的映射器启用或禁用缓存
    cache-enabled: true
    #全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载
    lazy-loading-enabled: true
    #当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载
    aggressive-lazy-loading: true
    #允许JDBC 生成主键。需要驱动器支持
    use-generated-keys: true
    #指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射　PARTIAL:部分  FULL:全部
    auto-mapping-behavior: partial
    #这是默认的执行类型（SIMPLE: 简单； REUSE: 执行器可能重复使用prepared statements语句；BATCH: 执行器可以重复执行语句和批量更新)
    default-executor-type: simple

    #控制台输出sql
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mybatis 别名
  type-aliases-package: com.bonc.entity
  #mapper_solr xml 扫描
  mapper-locations: mapper*/*Mapper.xml


#pagehepler
pagehelper:
  helper-dialect: mysql
  reasonable: "true"
  support-methods-arguments: "true"
  params: count=countSql

