#加密参数
jasypt:
  encryptor:
    password: hellojasypt
#tomcat 端口
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  session:
    #session超时时间 秒
    timeout: 1800

#核心Logger（包含嵌入式容器、hibernate、spring）会输出更多内容，
#但是你自己应用的日志并不会输出为DEBUG级别
debug: true

spring:
  #热部署生效
  devtools:
    restart:
      enabled: true
  #时间戳统一转换
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
  data:
    #mongodb数据源配置
    mongodb:
      host: 192.168.88.128
      port: 27017
      database: testDB
      repositories:
        enabled: true
    #solr数据源配置
    solr:
      host: http://192.168.88.128:8983/solr
      repositories:
        enabled: true
  #redis 数据源配置
  redis:
    # Redis服务器地址
    host: 192.168.88.128
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ENC(356IXRJuIUZGToRMUG375+pm5hnmyqM4)
    # 连接超时时间（毫秒）
    timeout: 60000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 1
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 60000
  #mysql数据源配置
  datasource:
    url: jdbc:mysql://192.168.88.128:3306/solrdb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: ENC(356IXRJuIUZGToRMUG375+pm5hnmyqM4)
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialize: true
